name: Docs

on:
  #push:
  #  branches-ignore:
  #    - '**'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: ➕ Install required packages
      run: brew install doxygen
        && brew install sphinx-doc
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-sitemap

    - name: 🚀 Checkout
      uses: actions/checkout@v2.3.2

    - name: ➕ Install cmake
      uses: jwlawson/actions-setup-cmake@v1.0
      with:
        cmake-version: '${{env.CMAKE_VERSION}}'
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: 👷 Build docs
      run: mkdir build
        && cd build
        && cmake -DCMAKE_INSTALL_PREFIX=../bin -DBUILD_DOCS=ON ..
        && make install
        && touch .nojekyll

    - name: 🚀 Deploy docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/Sphinx/html # The folder the action should deploy.
        SINGLE_COMMIT: true
